import json
from pathlib import Path

from portmap.cli import main


def write_portmap_toml(root: Path, *, dns_port: int = 53) -> None:
    (root / "portmap.toml").write_text(
        f"""
[gateway]
dns_bind = "0.0.0.0"
dns_port = {dns_port}
dns_domain = "debug.lan"
""".lstrip(),
        encoding="utf-8",
    )


def test_dns_set_writes_systemd_resolved_dropin(tmp_path: Path, monkeypatch, capsys) -> None:
    config_dir = tmp_path / "resolved.conf.d"
    write_portmap_toml(tmp_path)
    monkeypatch.setenv("PORTMAP_ROOT", str(tmp_path))
    monkeypatch.setattr("portmap.settings.detect_host_ip", lambda: "192.168.201.52")

    assert main(["dns", "set", "--config-dir", str(config_dir), "--no-sudo", "--no-restart"]) == 0

    path = config_dir / "90-portmap-debug-lan.conf"
    assert path.read_text(encoding="utf-8") == (
        "# Generated by portmap dns set. Remove with portmap dns unset.\n"
        "[Resolve]\n"
        "DNS=192.168.201.52\n"
        "Domains=~debug.lan\n"
    )
    payload = json.loads(capsys.readouterr().out)
    assert payload == {
        "action": "set",
        "dns_domain": "debug.lan",
        "dns_server": "192.168.201.52",
        "path": str(path),
        "restarted": False,
        "used_sudo": False,
    }


def test_dns_unset_removes_systemd_resolved_dropin(tmp_path: Path, monkeypatch, capsys) -> None:
    config_dir = tmp_path / "resolved.conf.d"
    config_dir.mkdir()
    path = config_dir / "90-portmap-debug-lan.conf"
    path.write_text("stale\n", encoding="utf-8")
    write_portmap_toml(tmp_path)
    monkeypatch.setenv("PORTMAP_ROOT", str(tmp_path))
    monkeypatch.setattr("portmap.settings.detect_host_ip", lambda: "192.168.201.52")

    assert main(["dns", "unset", "--config-dir", str(config_dir), "--no-sudo", "--no-restart"]) == 0

    assert not path.exists()
    payload = json.loads(capsys.readouterr().out)
    assert payload == {
        "action": "unset",
        "dns_domain": "debug.lan",
        "dns_server": "",
        "path": str(path),
        "restarted": False,
        "used_sudo": False,
    }


def test_dns_set_rejects_non_standard_dns_port(tmp_path: Path, monkeypatch, capsys) -> None:
    write_portmap_toml(tmp_path, dns_port=5353)
    monkeypatch.setenv("PORTMAP_ROOT", str(tmp_path))
    monkeypatch.setattr("portmap.settings.detect_host_ip", lambda: "192.168.201.52")

    assert main(["dns", "set", "--config-dir", str(tmp_path), "--no-sudo", "--no-restart"]) == 2

    assert "requires portmap DNS to listen on port 53" in capsys.readouterr().err
