from __future__ import annotations

import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .errors import PortmapError


DEFAULT_RESOLVED_CONF_DIR = Path("/etc/systemd/resolved.conf.d")


@dataclass(frozen=True)
class HostDnsResult:
    action: str
    dns_server: str
    dns_domain: str
    path: Path
    restarted: bool
    used_sudo: bool

    def as_dict(self) -> dict[str, str | bool]:
        return {
            "action": self.action,
            "dns_server": self.dns_server,
            "dns_domain": self.dns_domain,
            "path": str(self.path),
            "restarted": self.restarted,
            "used_sudo": self.used_sudo,
        }


def set_resolved_dropin(
    *,
    dns_server: str,
    dns_domain: str,
    dns_port: int = 53,
    config_dir: Path = DEFAULT_RESOLVED_CONF_DIR,
    restart: bool = True,
    use_sudo: bool = True,
) -> HostDnsResult:
    server, domain = normalize_dns_config(dns_server=dns_server, dns_domain=dns_domain, dns_port=dns_port)
    path = resolved_dropin_path(config_dir=config_dir, dns_domain=domain)
    content = render_resolved_dropin(dns_server=server, dns_domain=domain)
    used_sudo = should_use_sudo(use_sudo)

    if used_sudo:
        run_privileged(["mkdir", "-p", str(path.parent)], use_sudo=True)
        run_privileged(["tee", str(path)], input_text=content, stdout=subprocess.DEVNULL, use_sudo=True)
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    if restart:
        restart_systemd_resolved(use_sudo=use_sudo)

    return HostDnsResult(
        action="set",
        dns_server=server,
        dns_domain=domain,
        path=path,
        restarted=restart,
        used_sudo=used_sudo,
    )


def unset_resolved_dropin(
    *,
    dns_domain: str,
    config_dir: Path = DEFAULT_RESOLVED_CONF_DIR,
    restart: bool = True,
    use_sudo: bool = True,
) -> HostDnsResult:
    domain = normalize_dns_domain(dns_domain)
    path = resolved_dropin_path(config_dir=config_dir, dns_domain=domain)
    used_sudo = should_use_sudo(use_sudo)

    if used_sudo:
        run_privileged(["rm", "-f", str(path)], use_sudo=True)
    else:
        path.unlink(missing_ok=True)

    if restart:
        restart_systemd_resolved(use_sudo=use_sudo)

    return HostDnsResult(
        action="unset",
        dns_server="",
        dns_domain=domain,
        path=path,
        restarted=restart,
        used_sudo=used_sudo,
    )


def normalize_dns_config(*, dns_server: str, dns_domain: str, dns_port: int) -> tuple[str, str]:
    server = dns_server.strip()
    if not server:
        raise PortmapError("host DNS setup requires a DNS server")
    if dns_port != 53:
        raise PortmapError(
            "host DNS setup requires portmap DNS to listen on port 53; "
            f"current dns_port is {dns_port}"
        )
    return server, normalize_dns_domain(dns_domain)


def normalize_dns_domain(dns_domain: str) -> str:
    domain = dns_domain.strip().strip(".")
    if not domain:
        raise PortmapError("host DNS setup requires a DNS domain")
    return domain


def resolved_dropin_path(*, config_dir: Path, dns_domain: str) -> Path:
    return config_dir.expanduser() / f"90-portmap-{slug_dns_domain(dns_domain)}.conf"


def slug_dns_domain(dns_domain: str) -> str:
    slug = normalize_dns_domain(dns_domain).replace(".", "-")
    slug = re.sub(r"[^A-Za-z0-9_-]+", "-", slug).strip("-")
    if not slug:
        raise PortmapError(f"cannot derive resolved drop-in name from DNS domain: {dns_domain!r}")
    return slug


def render_resolved_dropin(*, dns_server: str, dns_domain: str) -> str:
    return (
        "# Generated by portmap dns set. Remove with portmap dns unset.\n"
        "[Resolve]\n"
        f"DNS={dns_server}\n"
        f"Domains=~{dns_domain}\n"
    )


def restart_systemd_resolved(*, use_sudo: bool) -> None:
    run_privileged(["systemctl", "restart", "systemd-resolved"], use_sudo=use_sudo)


def should_use_sudo(use_sudo: bool) -> bool:
    return use_sudo and hasattr(os, "geteuid") and os.geteuid() != 0


def run_privileged(
    command: list[str],
    *,
    use_sudo: bool,
    input_text: str | None = None,
    stdout=None,
) -> None:
    full_command = ["sudo", *command] if should_use_sudo(use_sudo) else command
    try:
        subprocess.run(
            full_command,
            check=True,
            input=input_text,
            text=True,
            stdout=stdout,
        )
    except FileNotFoundError as exc:
        raise PortmapError(f"failed to run {full_command[0]!r}: command not found") from exc
    except subprocess.CalledProcessError as exc:
        printable = " ".join(full_command)
        raise PortmapError(f"failed to run {printable!r} with exit code {exc.returncode}") from exc
